select 
	DOCUMENTOASSOCIADO,
	NRBA,
	CONTRATO,
	ATIVIDADE,
	DATAABERTURAOS,
	PROMOCAO,
	MUNICIPIO,
	DATAABERTURABA,
	ESTADO,
	INICIOAGENDAMENTO,
	INICIOEXECUCAO,
	FIMEXECUCAO,
	MATRICULATECNICO,
	SKILLS,
	DESC_FINAL,
	CODENCERRAMENTO
from
	CLICK_FECHADAS 
where
	PROMOCAO LIKE '%CP1%' 
and ATIVIDADE='RETIRADA BL'
and MUNICIPIO IN ('SETE LAGOAS','UBA')
and year(DATAABERTURABA)>=2021

UNION

select 
	DOCUMENTOASSOCIADO,
	NRBA,
	CONTRATO,
	ATIVIDADE,
	DATAABERTURAOS,
	PROMOCAO,
	MUNICIPIO,
	DATAABERTURABA,
	ESTADO,
	INICIOAGENDAMENTO,
	INICIOEXECUCAO,
	FIMEXECUCAO,
	MATRICULATECNICO,
	SKILLS,
	DESC_FINAL,
	CODENCERRAMENTO
from
	CLICK_ABERTAS 
where
	PROMOCAO LIKE '%CP1%' 
and ATIVIDADE='RETIRADA BL'
and MUNICIPIO IN ('SETE LAGOAS','UBA')
and year(DATAABERTURABA)>=2021
and DATAINDICADOR = (SELECT MAX(DATAINDICADOR) FROM CLICK_ABERTAS)


SELECT ESTADO, MATRICULATECNICO, ATIVIDADE,convert(varchar(10), FIMEXECUCAO, 120) ENCERRAMENTO, COUNT(*) QTE FROM CLICK_FECHADAS WHERE MATRICULATECNICO 
IN 
(
'TR689411'
,'TR672646'
,'TR670192'
,'TR683986'
,'TR347840'
,'TR680188'
) AND YEAR(FIMEXECUCAO) >='2021'
GROUP BY ESTADO, MATRICULATECNICO, ATIVIDADE,convert(varchar(10), FIMEXECUCAO, 120) 





